// action types
const constants = {
  QUESTIONS: 'QUESTIONS',
  ANSWERS: 'ANSWERS',
  ADD_CORRECT_ANSWERS: 'ADD_CORRECT_ANSWERS',
  ADD_ALMOST_RIGHT_ANSWERS: 'ADD_ALMOST_RIGHT_ANSWERS',
  ADD_WAY_OFF_ANSWERS: 'ADD_WAY_OFF_ANSWERS',
  ADD_DEAD_WRONG_ANSWERS: 'ADD_DEAD_WRONG_ANSWERS',
  MISSED_QUESTION: 'MISSED_QUESTION',
  SCORE_TALLY: 'SCORE_TALLY',
  COUNT: 'COUNT',
  SCORE: 'SCORE',
};

export default constants;
